### ISSUE TITLE
Change workout delete functionality to mark as deleted

### ISSUE THREAD

**Issue by agrahul89** [agrahul89/workout_tracker#1]
# Current
On Delete request workout is deleted from database.

# Change
On Delete request workout should be marked as deleted.

## TODO
 - [x] Update `workout` table to include a new column `deleted`
 - [x] Update `workout` bean to include a new field `deleted`
 - [x] Update `WorkoutController.deleteWorkout()` to update instead of delete a record, use `WorkoutController.updateWorkout`

**Comment by agrahul89** [comment]
Changes completed.
